CC = clang
CXX = clang++
FLAGS = -fopenmp -pthread -Wall -Wextra -march=native -Ofast
# FLAGS += -DDEBUG
# FLAGS += -DTIMING -lrt
CXXFLAGS = $(FLAGS)
CFLAGS = -lm $(FLAGS)

NVFLAGS  := -std=c++11 -O3 -Xptxas="-v" -arch=sm_61 
NVFLAGS += -Xcompiler "-fopenmp -pthread -Wall -Wextra -march=native"
# NVFLAGS += -DDEBUG
# NVFLAGS += -DTIMING -lrt
LDFLAGS  := -lm

EXES     := hw3-1 

alls: $(EXES)

clean:
	rm -f $(EXES)

seq: seq.cc
	$(CXX) $(CXXFLAGS) -o $@ $?

hw3-1: hw3-1.cc
	$(CXX) $(CXXFLAGS) -o $@ $?

# hw3-2: hw3-2.cu
# 	nvcc $(NVFLAGS) $(LDFLAGS) -o $@ $?

# hw3-3: hw3-3.cu
# 	nvcc $(NVFLAGS) $(LDFLAGS) -o $@ $?